#!/bin/bash

if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$1"
fi

xmessage -center Info: "Your time is up in 30 minutes. You will get a reminder wen you have 2 left." -title "Time Remaining Information"

sleep 28m
xmessage -center Warning: "Time is up in 2 minutes. Please save your work and shut down the computer or it will shut down for you." -title "Time is almost up."
sleep 2m

sudo shutdown now
